version: "3.8"

services:
  api:
    container_name: api
    build: . 
    volumes:
      - ./:/temp
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/root/myvenv #ここ書き換えて試してない
    command: uvicorn myvenv.main:app --reload --host 0.0.0.0 --port 8000
